<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "contact_form"
 *
 * Auto generated by Extension Builder 2018-10-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Lead Generation contact form',
    'description' => '',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'stable',
    'uploadfolder' => true,
    'createDirs' => '',
    'clearcacheonload' => true,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'flux' => '8.2.1',
            'fluidpages' => '4.1.0',
            'static_info_tables' => '6.7.0-8.99.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    'autoload' => [
        'classmap' => [
            'Classes',
            'Classes/Excel/PHPExcel.php',
        ]
    ]
];
