<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "silcoplast_product"
 *
 * Auto generated by Extension Builder 2019-04-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Silcoplast_Product',
    'description' => 'silcoplast_product',
    'category' => 'plugin',
    'author' => 'ons',
    'author_email' => 'ons.chaari@softtodo.com',
    'state' => 'experimental',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
