#
# Table structure for table 'tx_pingag_real_estate'
#
CREATE TABLE tx_pingag_real_estate (
	uid int(11) NOT NULL auto_increment,
	pid int(11) DEFAULT '0' NOT NULL,
	tstamp int(11) DEFAULT '0' NOT NULL,
	crdate int(11) DEFAULT '0' NOT NULL,
	cruser_id int(11) DEFAULT '0' NOT NULL,
	t3ver_oid int(11) DEFAULT '0' NOT NULL,
	t3ver_id int(11) DEFAULT '0' NOT NULL,
	t3ver_wsid int(11) DEFAULT '0' NOT NULL,
	t3ver_label varchar(30) DEFAULT '' NOT NULL,
	t3ver_state tinyint(4) DEFAULT '0' NOT NULL,
	t3ver_stage tinyint(4) DEFAULT '0' NOT NULL,
	t3ver_count int(11) DEFAULT '0' NOT NULL,
	t3ver_tstamp int(11) DEFAULT '0' NOT NULL,
  t3ver_move_id int(11) DEFAULT '0' NOT NULL,
	t3_origuid int(11) DEFAULT '0' NOT NULL,
	editlock tinyint(4) DEFAULT '0' NOT NULL,
	sys_language_uid int(11) DEFAULT '0' NOT NULL,
	l10n_parent int(11) DEFAULT '0' NOT NULL,
	l10n_diffsource mediumtext,
	deleted tinyint(4) DEFAULT '0' NOT NULL,
	hidden tinyint(4) DEFAULT '0' NOT NULL,
	starttime int(11) DEFAULT '0' NOT NULL,
	endtime int(11) DEFAULT '0' NOT NULL,
	sorting int(11) DEFAULT '0' NOT NULL,
	fe_group varchar(100) DEFAULT '0' NOT NULL,
	
	version varchar(50) DEFAULT '' NOT NULL,
	sender_id varchar(50) DEFAULT '' NOT NULL,
	last_modified varchar(50) DEFAULT '0' NOT NULL,
	url varchar(255) DEFAULT '' NOT NULL,
	sparefield_2 varchar(255) DEFAULT '' NOT NULL,
	object_category varchar(25) DEFAULT '' NOT NULL,
	object_type int(3) DEFAULT '0' NOT NULL,
	offer_type varchar(200) DEFAULT '' NOT NULL,
	ref_property varchar(80) DEFAULT '' NOT NULL,
	ref_house varchar(80) DEFAULT '' NOT NULL,
	ref_object varchar(80) DEFAULT '' NOT NULL,
	object_street varchar(200) DEFAULT '' NOT NULL,
	object_zip varchar(10) DEFAULT '' NOT NULL,
	object_city varchar(200) DEFAULT '' NOT NULL,
	object_state varchar(2) DEFAULT '' NOT NULL,
	object_country varchar(2) DEFAULT '' NOT NULL,
	region varchar(200) DEFAULT '' NOT NULL,
	object_situation varchar(50) DEFAULT '' NOT NULL,

	object_x varchar(200) DEFAULT '' NOT NULL,
	object_y varchar(200) DEFAULT '' NOT NULL,

	available_from varchar(11) DEFAULT '0' NOT NULL,
	object_title varchar(70) DEFAULT '' NOT NULL,
	object_description text,
	selling_price int(10) DEFAULT '0' NOT NULL,
	rent_net int(10) DEFAULT '0' NOT NULL,
	rent_extra int(10) DEFAULT '0' NOT NULL,
	price_unit varchar(10) DEFAULT '' NOT NULL,
	price int(10) DEFAULT '0' NOT NULL,
	currency varchar(3) DEFAULT '' NOT NULL,
	
	minergie_general varchar(1) DEFAULT '' NOT NULL,
	prop_elevator varchar(1) DEFAULT '' NOT NULL,
	prop_balcony varchar(1) DEFAULT '' NOT NULL,
	prop_parking varchar(1) DEFAULT '' NOT NULL,
	prop_garage varchar(1) DEFAULT '' NOT NULL,
	prop_child_friendly varchar(1) DEFAULT '' NOT NULL,
	prop_view varchar(1) DEFAULT '' NOT NULL,
	prop_cabletv varchar(1) DEFAULT '' NOT NULL,
	prop_fireplace varchar(1) DEFAULT '' NOT NULL,
	isdn varchar(1) DEFAULT '' NOT NULL,
	new_building varchar(1) DEFAULT '' NOT NULL,
	distance_public_transport int(5) DEFAULT '0' NOT NULL,
	wheelchair_accessible varchar(1) DEFAULT '' NOT NULL,
	animal_allowed varchar(1) DEFAULT '' NOT NULL,
	ramp varchar(1) DEFAULT '' NOT NULL,
	railway_terminal varchar(1) DEFAULT '' NOT NULL,
	
	gross_premium varchar(19) DEFAULT '' NOT NULL,
	floor int(6) DEFAULT '0' NOT NULL,
	number_of_rooms decimal(2,1) DEFAULT '0' NOT NULL,
	number_of_floors int(5) DEFAULT '0' NOT NULL,
	number_of_apartments int(5) DEFAULT '0' NOT NULL,
	surface_living int(10) DEFAULT '0' NOT NULL,
	surface_usable int(10) DEFAULT '0' NOT NULL,
	surface_property int(10) DEFAULT '0' NOT NULL,
	year_built int(4) DEFAULT '0' NOT NULL,
	year_renovated int(4) DEFAULT '0' NOT NULL,
	
	distance_shop int(5) DEFAULT '0' NOT NULL,
	distance_kindergarten int(5) DEFAULT '0' NOT NULL,
	distance_school1 int(5) DEFAULT '0' NOT NULL,
	distance_school2 int(5) DEFAULT '0' NOT NULL,
	distance_motorway int(5) DEFAULT '0' NOT NULL,
	
	agency_id varchar(10) DEFAULT '' NOT NULL,
	agency_name varchar(200) DEFAULT '' NOT NULL,
	agency_name_2 varchar(200) DEFAULT '' NOT NULL,
	agency_reference varchar(200) DEFAULT '' NOT NULL,
	agency_phone varchar(200) DEFAULT '' NOT NULL,
	agency_fax varchar(200) DEFAULT '' NOT NULL,
	agency_email varchar(200) DEFAULT '' NOT NULL,
	agency_street varchar(200) DEFAULT '' NOT NULL,
	agency_zip varchar(200) DEFAULT '' NOT NULL,
	agency_city varchar(200) DEFAULT '' NOT NULL,

	visit_name varchar(200) DEFAULT '' NOT NULL,
	visit_phone varchar(200) DEFAULT '' NOT NULL,
	visit_email varchar(200) DEFAULT '' NOT NULL,
	
	pictures int(11) unsigned DEFAULT '0',
	documents int(11) unsigned DEFAULT '0',

	PRIMARY KEY (uid),
	KEY parent (pid),
	KEY sys_language_uid_l10n_parent (sys_language_uid,l10n_parent),
);