<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pingag_real_estate"
 *
 * Auto generated by Extension Builder 2017-07-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Immobilien Tool',
    'description' => 'Immport und Anzeige von Immobilien im IDX Format',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.3.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
