<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fag_institution_management"
 *
 * Auto generated by Extension Builder 2019-03-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'FRONTAL / Institutionen',
    'description' => 'Allows the administration of various institutions.',
    'category' => 'plugin',
    'author' => 'Roland Kneubühler',
    'author_email' => 'rk@frontal.ch',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.8.7',
    'constraints' => [
        'depends' => [
            'fag_extbase' => '1.1.1',
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
