<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pingag_standard_helper"
 *
 * Auto generated by Extension Builder 2017-07-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Thurcom Extension',
    'description' => 'Sender, Produkteberater, Zubehör und Partner',
    'category' => 'plugin',
    'author' => 'Cyrill Gsell',
    'author_email' => 'cyrill.gsell@pingag.ch',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.4-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
