#
# Table structure for table 'pages'
#
CREATE TABLE pages (
  show_subnavigation  TINYINT(4) DEFAULT '0'       NOT NULL,
  class_subnavigation  VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TABLE tt_content (
  tx_logifact_camaliga    VARCHAR(255) NOT NULL DEFAULT '',
  tx_logifact_slide       VARCHAR(255) NOT NULL DEFAULT '',
  tx_logifact_opinion     VARCHAR(255) NOT NULL DEFAULT '',
  tx_logifact_tab         VARCHAR(255) NOT NULL DEFAULT '',
  tx_logifact_teaser_big  VARCHAR(255) NOT NULL DEFAULT '',
  tx_logifact_link        VARCHAR(255) NOT NULL DEFAULT '',
  tx_logifact_service     VARCHAR(255) NOT NULL DEFAULT '',
  tx_logifact_product     VARCHAR(255) NOT NULL DEFAULT '',
  tx_logifact_cobra_product VARCHAR(255) NOT NULL DEFAULT '',
  tx_logifact_file_tab    VARCHAR(255) NOT NULL DEFAULT '',
  tx_logifact_team        VARCHAR(255) NOT NULL DEFAULT '',
  tx_logifact_footer_button VARCHAR(255) NOT NULL DEFAULT '',
  body_text               TEXT,
  link                    VARCHAR(1024) NOT NULL DEFAULT '',
  link_title              VARCHAR(255) NOT NULL DEFAULT '',
  show_header             TINYINT(4) DEFAULT '0'       NOT NULL
);


CREATE TABLE tx_logifact_camaliga (
  uid              INT(11)                         NOT NULL AUTO_INCREMENT,
  pid              INT(11) DEFAULT '0'             NOT NULL,

  title            VARCHAR(255)                    NOT NULL DEFAULT '',
  subtitle          TEXT                            NOT NULL DEFAULT '',
  link             VARCHAR(255)                    NOT NULL DEFAULT '',
  image            INT(11) UNSIGNED DEFAULT '0'    NOT NULL,

  parent_uid       INT(11) DEFAULT '0'             NOT NULL,

  deleted          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  hidden           TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sorting          INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_oid        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_id         INT(11) DEFAULT '0'             NOT NULL,
  t3ver_wsid       INT(11) DEFAULT '0'             NOT NULL,
  t3ver_label      VARCHAR(255) DEFAULT ''         NOT NULL,
  t3ver_state      TINYINT(4) DEFAULT '0'          NOT NULL,
  t3ver_stage      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_count      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_tstamp     INT(11) DEFAULT '0'             NOT NULL,
  t3ver_move_id    INT(11) DEFAULT '0'             NOT NULL,
  tstamp           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  crdate           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  cruser_id        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  starttime        TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  endtime          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sys_language_uid INT(11) DEFAULT '0'             NOT NULL,
  l10n_state       INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_parent      INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_diffsource  MEDIUMBLOB,
  PRIMARY KEY (uid),
  KEY parent (pid),
  KEY t3ver_oid (t3ver_oid, t3ver_wsid),
  KEY language (l10n_parent, sys_language_uid)
);

CREATE TABLE tx_logifact_slide (
  uid              INT(11)                         NOT NULL AUTO_INCREMENT,
  pid              INT(11) DEFAULT '0'             NOT NULL,

  title            VARCHAR(255)                    NOT NULL DEFAULT '',
  content          TEXT                            NOT NULL DEFAULT '',
  link             VARCHAR(255)                    NOT NULL DEFAULT '',
  buttonimage      INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  image            INT(11) UNSIGNED DEFAULT '0'    NOT NULL,

  parent_uid       INT(11) DEFAULT '0'             NOT NULL,
  deleted          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  hidden           TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sorting          INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_oid        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_id         INT(11) DEFAULT '0'             NOT NULL,
  t3ver_wsid       INT(11) DEFAULT '0'             NOT NULL,
  t3ver_label      VARCHAR(255) DEFAULT ''         NOT NULL,
  t3ver_state      TINYINT(4) DEFAULT '0'          NOT NULL,
  t3ver_stage      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_count      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_tstamp     INT(11) DEFAULT '0'             NOT NULL,
  t3ver_move_id    INT(11) DEFAULT '0'             NOT NULL,
  tstamp           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  crdate           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  cruser_id        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  starttime        TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  endtime          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sys_language_uid INT(11) DEFAULT '0'             NOT NULL,
  l10n_state       INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_parent      INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_diffsource  MEDIUMBLOB,
  PRIMARY KEY (uid),
  KEY parent (pid),
  KEY t3ver_oid (t3ver_oid, t3ver_wsid),
  KEY language (l10n_parent, sys_language_uid)
);


CREATE TABLE tx_logifact_opinion (
  uid              INT(11)                         NOT NULL AUTO_INCREMENT,
  pid              INT(11) DEFAULT '0'             NOT NULL,

  name             VARCHAR(255)                    NOT NULL DEFAULT '',
  opinion          TEXT                            NOT NULL DEFAULT '',
  company          VARCHAR(255)                    NOT NULL DEFAULT '',

  parent_uid       INT(11) DEFAULT '0'             NOT NULL,
  deleted          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  hidden           TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sorting          INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_oid        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_id         INT(11) DEFAULT '0'             NOT NULL,
  t3ver_wsid       INT(11) DEFAULT '0'             NOT NULL,
  t3ver_label      VARCHAR(255) DEFAULT ''         NOT NULL,
  t3ver_state      TINYINT(4) DEFAULT '0'          NOT NULL,
  t3ver_stage      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_count      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_tstamp     INT(11) DEFAULT '0'             NOT NULL,
  t3ver_move_id    INT(11) DEFAULT '0'             NOT NULL,
  tstamp           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  crdate           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  cruser_id        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  starttime        TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  endtime          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sys_language_uid INT(11) DEFAULT '0'             NOT NULL,
  l10n_state       INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_parent      INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_diffsource  MEDIUMBLOB,
  PRIMARY KEY (uid),
  KEY parent (pid),
  KEY t3ver_oid (t3ver_oid, t3ver_wsid),
  KEY language (l10n_parent, sys_language_uid)
);


CREATE TABLE tx_logifact_tab (
  uid              INT(11)                         NOT NULL AUTO_INCREMENT,
  pid              INT(11) DEFAULT '0'             NOT NULL,

  title            VARCHAR(255)                    NOT NULL DEFAULT '',
  content          TEXT                            NOT NULL DEFAULT '',

  parent_uid       INT(11) DEFAULT '0'             NOT NULL,
  deleted          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  hidden           TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sorting          INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_oid        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_id         INT(11) DEFAULT '0'             NOT NULL,
  t3ver_wsid       INT(11) DEFAULT '0'             NOT NULL,
  t3ver_label      VARCHAR(255) DEFAULT ''         NOT NULL,
  t3ver_state      TINYINT(4) DEFAULT '0'          NOT NULL,
  t3ver_stage      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_count      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_tstamp     INT(11) DEFAULT '0'             NOT NULL,
  t3ver_move_id    INT(11) DEFAULT '0'             NOT NULL,
  tstamp           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  crdate           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  cruser_id        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  starttime        TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  endtime          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sys_language_uid INT(11) DEFAULT '0'             NOT NULL,
  l10n_state       INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_parent      INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_diffsource  MEDIUMBLOB,
  PRIMARY KEY (uid),
  KEY parent (pid),
  KEY t3ver_oid (t3ver_oid, t3ver_wsid),
  KEY language (l10n_parent, sys_language_uid)
);
CREATE TABLE tx_logifact_link (
  uid              INT(11)                         NOT NULL AUTO_INCREMENT,
  pid              INT(11) DEFAULT '0'             NOT NULL,

  title            VARCHAR(255)                    NOT NULL DEFAULT '',
  link             VARCHAR(255)                    NOT NULL DEFAULT '',

  parent_uid       INT(11) DEFAULT '0'             NOT NULL,
  deleted          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  hidden           TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sorting          INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_oid        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_id         INT(11) DEFAULT '0'             NOT NULL,
  t3ver_wsid       INT(11) DEFAULT '0'             NOT NULL,
  t3ver_label      VARCHAR(255) DEFAULT ''         NOT NULL,
  t3ver_state      TINYINT(4) DEFAULT '0'          NOT NULL,
  t3ver_stage      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_count      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_tstamp     INT(11) DEFAULT '0'             NOT NULL,
  t3ver_move_id    INT(11) DEFAULT '0'             NOT NULL,
  tstamp           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  crdate           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  cruser_id        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  starttime        TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  endtime          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sys_language_uid INT(11) DEFAULT '0'             NOT NULL,
  l10n_state       INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_parent      INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_diffsource  MEDIUMBLOB,
  PRIMARY KEY (uid),
  KEY parent (pid),
  KEY t3ver_oid (t3ver_oid, t3ver_wsid),
  KEY language (l10n_parent, sys_language_uid)
);

CREATE TABLE tx_logifact_teaser_big(
  uid              INT(11)                         NOT NULL AUTO_INCREMENT,
  pid              INT(11) DEFAULT '0'             NOT NULL,

  title            VARCHAR(255)                    NOT NULL DEFAULT '',
  content          TEXT                            NOT NULL DEFAULT '',
  link             VARCHAR(255)                    NOT NULL DEFAULT '',
  image            INT(11) UNSIGNED DEFAULT '0'    NOT NULL,

  parent_uid       INT(11) DEFAULT '0'             NOT NULL,
  deleted          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  hidden           TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sorting          INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_oid        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_id         INT(11) DEFAULT '0'             NOT NULL,
  t3ver_wsid       INT(11) DEFAULT '0'             NOT NULL,
  t3ver_label      VARCHAR(255) DEFAULT ''         NOT NULL,
  t3ver_state      TINYINT(4) DEFAULT '0'          NOT NULL,
  t3ver_stage      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_count      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_tstamp     INT(11) DEFAULT '0'             NOT NULL,
  t3ver_move_id    INT(11) DEFAULT '0'             NOT NULL,
  tstamp           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  crdate           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  cruser_id        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  starttime        TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  endtime          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sys_language_uid INT(11) DEFAULT '0'             NOT NULL,
  l10n_state       INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_parent      INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_diffsource  MEDIUMBLOB,
  PRIMARY KEY (uid),
  KEY parent (pid),
  KEY t3ver_oid (t3ver_oid, t3ver_wsid),
  KEY language (l10n_parent, sys_language_uid)
);
CREATE TABLE tx_logifact_cobra_product(
  uid              INT(11)                         NOT NULL AUTO_INCREMENT,
  pid              INT(11) DEFAULT '0'             NOT NULL,

  title            VARCHAR(255)                    NOT NULL DEFAULT '',
  link_title       VARCHAR(255)                    NOT NULL DEFAULT '',
  content          TEXT                            NOT NULL DEFAULT '',
  link             VARCHAR(255)                    NOT NULL DEFAULT '',
  image            INT(11) UNSIGNED DEFAULT '0'    NOT NULL,

  parent_uid       INT(11) DEFAULT '0'             NOT NULL,
  deleted          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  hidden           TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sorting          INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_oid        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_id         INT(11) DEFAULT '0'             NOT NULL,
  t3ver_wsid       INT(11) DEFAULT '0'             NOT NULL,
  t3ver_label      VARCHAR(255) DEFAULT ''         NOT NULL,
  t3ver_state      TINYINT(4) DEFAULT '0'          NOT NULL,
  t3ver_stage      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_count      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_tstamp     INT(11) DEFAULT '0'             NOT NULL,
  t3ver_move_id    INT(11) DEFAULT '0'             NOT NULL,
  tstamp           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  crdate           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  cruser_id        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  starttime        TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  endtime          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sys_language_uid INT(11) DEFAULT '0'             NOT NULL,
  l10n_state       INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_parent      INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_diffsource  MEDIUMBLOB,
  PRIMARY KEY (uid),
  KEY parent (pid),
  KEY t3ver_oid (t3ver_oid, t3ver_wsid),
  KEY language (l10n_parent, sys_language_uid)
);

CREATE TABLE tx_logifact_service(
  uid              INT(11)                         NOT NULL AUTO_INCREMENT,
  pid              INT(11) DEFAULT '0'             NOT NULL,

  title            VARCHAR(255)                    NOT NULL DEFAULT '',
  content          TEXT                            NOT NULL DEFAULT '',
  image            INT(11) UNSIGNED DEFAULT '0'    NOT NULL,

  parent_uid       INT(11) DEFAULT '0'             NOT NULL,
  deleted          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  hidden           TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sorting          INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_oid        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_id         INT(11) DEFAULT '0'             NOT NULL,
  t3ver_wsid       INT(11) DEFAULT '0'             NOT NULL,
  t3ver_label      VARCHAR(255) DEFAULT ''         NOT NULL,
  t3ver_state      TINYINT(4) DEFAULT '0'          NOT NULL,
  t3ver_stage      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_count      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_tstamp     INT(11) DEFAULT '0'             NOT NULL,
  t3ver_move_id    INT(11) DEFAULT '0'             NOT NULL,
  tstamp           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  crdate           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  cruser_id        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  starttime        TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  endtime          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sys_language_uid INT(11) DEFAULT '0'             NOT NULL,
  l10n_state       INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_parent      INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_diffsource  MEDIUMBLOB,
  PRIMARY KEY (uid),
  KEY parent (pid),
  KEY t3ver_oid (t3ver_oid, t3ver_wsid),
  KEY language (l10n_parent, sys_language_uid)
);
CREATE TABLE tx_logifact_product(
  uid              INT(11)                         NOT NULL AUTO_INCREMENT,
  pid              INT(11) DEFAULT '0'             NOT NULL,

  title            VARCHAR(255)                    NOT NULL DEFAULT '',
  content          TEXT                            NOT NULL DEFAULT '',
  image            INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  link_title       VARCHAR(255)                    NOT NULL DEFAULT '',
  link             VARCHAR(255)                    NOT NULL DEFAULT '',

  parent_uid       INT(11) DEFAULT '0'             NOT NULL,
  deleted          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  hidden           TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sorting          INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_oid        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_id         INT(11) DEFAULT '0'             NOT NULL,
  t3ver_wsid       INT(11) DEFAULT '0'             NOT NULL,
  t3ver_label      VARCHAR(255) DEFAULT ''         NOT NULL,
  t3ver_state      TINYINT(4) DEFAULT '0'          NOT NULL,
  t3ver_stage      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_count      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_tstamp     INT(11) DEFAULT '0'             NOT NULL,
  t3ver_move_id    INT(11) DEFAULT '0'             NOT NULL,
  tstamp           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  crdate           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  cruser_id        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  starttime        TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  endtime          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sys_language_uid INT(11) DEFAULT '0'             NOT NULL,
  l10n_state       INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_parent      INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_diffsource  MEDIUMBLOB,
  PRIMARY KEY (uid),
  KEY parent (pid),
  KEY t3ver_oid (t3ver_oid, t3ver_wsid),
  KEY language (l10n_parent, sys_language_uid)
);
CREATE TABLE tx_logifact_team(
  uid              INT(11)                         NOT NULL AUTO_INCREMENT,
  pid              INT(11) DEFAULT '0'             NOT NULL,

  name              VARCHAR(255)                    NOT NULL DEFAULT '',
  job_title         VARCHAR(255)                    NOT NULL DEFAULT '',
  image             INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  phone             VARCHAR(255)                    NOT NULL DEFAULT '',
  email             VARCHAR(255)                    NOT NULL DEFAULT '',

  parent_uid       INT(11) DEFAULT '0'             NOT NULL,
  deleted          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  hidden           TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sorting          INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_oid        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_id         INT(11) DEFAULT '0'             NOT NULL,
  t3ver_wsid       INT(11) DEFAULT '0'             NOT NULL,
  t3ver_label      VARCHAR(255) DEFAULT ''         NOT NULL,
  t3ver_state      TINYINT(4) DEFAULT '0'          NOT NULL,
  t3ver_stage      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_count      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_tstamp     INT(11) DEFAULT '0'             NOT NULL,
  t3ver_move_id    INT(11) DEFAULT '0'             NOT NULL,
  tstamp           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  crdate           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  cruser_id        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  starttime        TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  endtime          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sys_language_uid INT(11) DEFAULT '0'             NOT NULL,
  l10n_state       INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_parent      INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_diffsource  MEDIUMBLOB,
  PRIMARY KEY (uid),
  KEY parent (pid),
  KEY t3ver_oid (t3ver_oid, t3ver_wsid),
  KEY language (l10n_parent, sys_language_uid)
);
CREATE TABLE tx_logifact_file_tab(
  uid              INT(11)                         NOT NULL AUTO_INCREMENT,
  pid              INT(11) DEFAULT '0'             NOT NULL,

  title              VARCHAR(255)                    NOT NULL DEFAULT '',
  slides         VARCHAR(255)                    NOT NULL DEFAULT '',

  parent_uid       INT(11) DEFAULT '0'             NOT NULL,
  deleted          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  hidden           TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sorting          INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_oid        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_id         INT(11) DEFAULT '0'             NOT NULL,
  t3ver_wsid       INT(11) DEFAULT '0'             NOT NULL,
  t3ver_label      VARCHAR(255) DEFAULT ''         NOT NULL,
  t3ver_state      TINYINT(4) DEFAULT '0'          NOT NULL,
  t3ver_stage      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_count      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_tstamp     INT(11) DEFAULT '0'             NOT NULL,
  t3ver_move_id    INT(11) DEFAULT '0'             NOT NULL,
  tstamp           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  crdate           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  cruser_id        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  starttime        TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  endtime          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sys_language_uid INT(11) DEFAULT '0'             NOT NULL,
  l10n_state       INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_parent      INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_diffsource  MEDIUMBLOB,
  PRIMARY KEY (uid),
  KEY parent (pid),
  KEY t3ver_oid (t3ver_oid, t3ver_wsid),
  KEY language (l10n_parent, sys_language_uid)
);
CREATE TABLE tx_logifact_footer_button(
  uid              INT(11)                         NOT NULL AUTO_INCREMENT,
  pid              INT(11) DEFAULT '0'             NOT NULL,

  title            VARCHAR(255)                    NOT NULL DEFAULT '',
  link             VARCHAR(255)                    NOT NULL DEFAULT '',
  content          TEXT                            NOT NULL DEFAULT '',
  parent_uid       INT(11) DEFAULT '0'             NOT NULL,
  deleted          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  hidden           TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sorting          INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_oid        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  t3ver_id         INT(11) DEFAULT '0'             NOT NULL,
  t3ver_wsid       INT(11) DEFAULT '0'             NOT NULL,
  t3ver_label      VARCHAR(255) DEFAULT ''         NOT NULL,
  t3ver_state      TINYINT(4) DEFAULT '0'          NOT NULL,
  t3ver_stage      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_count      INT(11) DEFAULT '0'             NOT NULL,
  t3ver_tstamp     INT(11) DEFAULT '0'             NOT NULL,
  t3ver_move_id    INT(11) DEFAULT '0'             NOT NULL,
  tstamp           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  crdate           INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  cruser_id        INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  starttime        TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  endtime          TINYINT(4) UNSIGNED DEFAULT '0' NOT NULL,
  sys_language_uid INT(11) DEFAULT '0'             NOT NULL,
  l10n_state       INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_parent      INT(11) UNSIGNED DEFAULT '0'    NOT NULL,
  l10n_diffsource  MEDIUMBLOB,
  PRIMARY KEY (uid),
  KEY parent (pid),
  KEY t3ver_oid (t3ver_oid, t3ver_wsid),
  KEY language (l10n_parent, sys_language_uid)
);